--sql {#snowflake_setup}
-- Use an admin role
USE ROLE ACCOUNTADMIN;

-- Create the `transform` role
DROP ROLE IF EXISTS TRANSFORM;
CREATE ROLE TRANSFORM;
GRANT ROLE TRANSFORM TO ROLE ACCOUNTADMIN;

-- Create the default warehouse if necessary
GRANT OPERATE ON WAREHOUSE COMPUTE_WH TO ROLE TRANSFORM;

-- Create the `dbt` user and assign to role
DROP USER IF EXISTS dbt;
CREATE USER IF NOT EXISTS dbt
  LOGIN_NAME='dbt'
  TYPE=SERVICE
  RSA_PUBLIC_KEY="-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlD7Swrrq3u03vMiBxIWw
tIo2HfjGEywGc+lYtTfaEbIFq8aVz11F+/nFvNZkEijXNqVT9x547R12KYAA9aAb
kmvp78ww5x85gY/SA2R0RNnTS9FhnutdopqaheR5OBGjqKuRzng/tTMyshoGBMe/
Zpm7PVAHJ2EC6vQ0XLVoS4jS98iW8tynhyi20uP7fRZsDqESONbZhmveilb/lQpP
fYEBOGCyfghDWUfblQ28lUsbyB9GyFc3MiCOK4wFwKvEHBMGq/y8DsKl1NhPn/tB
YdY5R57lIbzTaZZyvDoIHXELT3yvl+TY6Xe1OJoF/0hK70oNFKYBdOLQPyMB28Ow
jQIDAQAB
-----END PUBLIC KEY-----"
  DEFAULT_ROLE=TRANSFORM
  DEFAULT_WAREHOUSE='COMPUTE_WH'
  DEFAULT_NAMESPACE='AIRBNB.RAW'
  COMMENT='DBT user used for data transformation';

GRANT ROLE TRANSFORM to USER dbt;

-- Set up permissions to role `transform`
GRANT ALL ON WAREHOUSE COMPUTE_WH TO ROLE TRANSFORM;
GRANT ALL ON DATABASE AIRBNB to ROLE TRANSFORM;
GRANT ALL ON ALL SCHEMAS IN DATABASE AIRBNB to ROLE TRANSFORM;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE AIRBNB to ROLE TRANSFORM;
GRANT ALL ON ALL TABLES IN SCHEMA AIRBNB.RAW to ROLE TRANSFORM;
GRANT ALL ON FUTURE TABLES IN SCHEMA AIRBNB.RAW to ROLE TRANSFORM;

-- Create the user and permissions for Preset.io
USE ROLE ACCOUNTADMIN;

DROP ROLE IF EXISTS REPORTER;
CREATE ROLE REPORTER;

DROP USER IF EXISTS PRESET;
CREATE USER PRESET
  LOGIN_NAME='preset'
  TYPE=SERVICE
  RSA_PUBLIC_KEY="-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlD7Swrrq3u03vMiBxIWw
tIo2HfjGEywGc+lYtTfaEbIFq8aVz11F+/nFvNZkEijXNqVT9x547R12KYAA9aAb
kmvp78ww5x85gY/SA2R0RNnTS9FhnutdopqaheR5OBGjqKuRzng/tTMyshoGBMe/
Zpm7PVAHJ2EC6vQ0XLVoS4jS98iW8tynhyi20uP7fRZsDqESONbZhmveilb/lQpP
fYEBOGCyfghDWUfblQ28lUsbyB9GyFc3MiCOK4wFwKvEHBMGq/y8DsKl1NhPn/tB
YdY5R57lIbzTaZZyvDoIHXELT3yvl+TY6Xe1OJoF/0hK70oNFKYBdOLQPyMB28Ow
jQIDAQAB
-----END PUBLIC KEY-----"
  DEFAULT_WAREHOUSE='COMPUTE_WH'
  DEFAULT_ROLE=REPORTER
  DEFAULT_NAMESPACE='AIRBNB.DEV'
 COMMENT='Preset user for creating reports';

GRANT ROLE REPORTER TO USER PRESET;
GRANT ROLE REPORTER TO ROLE ACCOUNTADMIN;
GRANT ALL ON WAREHOUSE COMPUTE_WH TO ROLE REPORTER;
GRANT USAGE ON DATABASE AIRBNB TO ROLE REPORTER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE AIRBNB to ROLE REPORTER;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE AIRBNB to ROLE REPORTER;
GRANT SELECT ON ALL TABLES IN SCHEMA AIRBNB.DEV to ROLE REPORTER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA AIRBNB.DEV to ROLE REPORTER;